name: Create branch from new issue

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to create branch for'
        required: true
        type: string
      issue_title:
        description: 'Issue title for branch name'
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create and push branch
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          ISSUE_NUMBER="${{ github.event.inputs.issue_number }}"
          ISSUE_TITLE="${{ github.event.inputs.issue_title }}"
        else
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE="${{ github.event.issue.title }}"
        fi
        
        # Clean the title for branch name
        SLUG=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
        
        # Truncate if too long
        if [ ${#SLUG} -gt 40 ]; then
          SLUG=$(echo "$SLUG" | cut -c1-40)
        fi
        
        BRANCH_NAME="issue-${ISSUE_NUMBER}-${SLUG}"
        
        echo "Creating branch: $BRANCH_NAME"
        git checkout -b "$BRANCH_NAME"
        git push origin "$BRANCH_NAME"

    - name: Comment on issue
      uses: actions/github-script@v7
      if: github.event_name == 'issues'
      with:
        script: |
          const issueNumber = ${{ github.event.issue.number }};
          const issueTitle = `${{ github.event.issue.title }}`;
          
          // Clean title for branch name
          const slug = issueTitle
            .toLowerCase()
            .replace(/[^a-z0-9]/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '')
            .substring(0, 40);
          
          const branchName = `issue-${issueNumber}-${slug}`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: `🌱 **Branch created automatically!**

Branch: \`${branchName}\`

You can start working on this issue:
\`\`\`bash
git fetch origin
git checkout ${branchName}
\`\`\`

Happy coding! 🚀`
          });
